// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOWIFHTwtnz-Lhc3-9XcK7qTqiEzmXgM4',
    appId: '1:234611071510:web:296ca120f180177cdeb337',
    messagingSenderId: '234611071510',
    projectId: 'chem-manager',
    authDomain: 'chem-manager.firebaseapp.com',
    storageBucket: 'chem-manager.firebasestorage.app',
    measurementId: 'G-ZDQLWP4KZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHCgGQjo4C6kuNvk8h3m3GrGiWWf4vmnQ',
    appId: '1:234611071510:android:bdb515bc7c35f1aedeb337',
    messagingSenderId: '234611071510',
    projectId: 'chem-manager',
    storageBucket: 'chem-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXj8cHFFSrYU9fKLh3LRAarngACV8pJMQ',
    appId: '1:234611071510:ios:0ca6ea5f7de2628cdeb337',
    messagingSenderId: '234611071510',
    projectId: 'chem-manager',
    storageBucket: 'chem-manager.firebasestorage.app',
    androidClientId: '234611071510-jvk4qrfsma43hohvkpb4m2t17evv324k.apps.googleusercontent.com',
    iosClientId: '234611071510-53jbiorvr6t12tnghlppfa39n828qg14.apps.googleusercontent.com',
    iosBundleId: 'com.example.chemManagerUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXj8cHFFSrYU9fKLh3LRAarngACV8pJMQ',
    appId: '1:234611071510:ios:0ca6ea5f7de2628cdeb337',
    messagingSenderId: '234611071510',
    projectId: 'chem-manager',
    storageBucket: 'chem-manager.firebasestorage.app',
    androidClientId: '234611071510-jvk4qrfsma43hohvkpb4m2t17evv324k.apps.googleusercontent.com',
    iosClientId: '234611071510-53jbiorvr6t12tnghlppfa39n828qg14.apps.googleusercontent.com',
    iosBundleId: 'com.example.chemManagerUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD85UVm9YDMmX24NZbJkPHRg5G7SV20GZ8',
    appId: '1:234611071510:web:1e77831504c3dc09deb337',
    messagingSenderId: '234611071510',
    projectId: 'chem-manager',
    authDomain: 'chem-manager.firebaseapp.com',
    storageBucket: 'chem-manager.firebasestorage.app',
    measurementId: 'G-9ESW8JN5FK',
  );
}
